### ISSUE TITLE
How to solve "Enable text compression" Lighthouse performance error when running through Netlify Plugin

### ISSUE THREAD

**Issue by griable** [netlify-labs/netlify-plugin-lighthouse#221]
I'm trying to see if I can move a frontend oriented CI to Netlify.
One of the features I'm expecting is getting Lighthouse score and thresholds to work.

However, it seems that, because this plugin relies on puppeteer and http-server, gzip compression is not enabled leading to a poor performance grade making it unusable for us.

<img width="744" alt="Screenshot 2021-06-08 at 16 26 33" src="https://user-images.githubusercontent.com/193908/121203659-92d41200-c876-11eb-83b2-2c9af9cc12b5.png">

<img width="898" alt="Screenshot 2021-06-08 at 16 26 25" src="https://user-images.githubusercontent.com/193908/121203677-96679900-c876-11eb-8273-ec0f15b7573b.png">

Any idea how to get this sorted? I'm willing to help with a PR if any of you have a pointer to sort this out.

Many thanks!

**Comment by erezrokah** [comment]
Hi @griable! That's a very good point.
Looking at https://github.com/http-party/http-server/issues/56 it doesn't seem it has built in support for compression.

We could switch to https://expressjs.com/en/starter/static-files.html and http://expressjs.com/en/resources/middleware/compression.html if that works, or any other static server that supports it.

Also we have a discussion in https://github.com/netlify-labs/netlify-plugin-lighthouse/issues/152#issuecomment-824198174 to audit the live URL instead of using a local server, however that might take longer to implement.
